name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  push:
    branches:
      - main
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          includeForks: false # Set to true if you want to include forked repositories
          readme: './README.md'

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with GitHub stats' || echo "No changes to commit"
          git push

      - name: Check Rate Limit
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit

      - name: Retry Step
        id: retry_step
        run: |
          for i in {1..3}; do
            if curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/graphql; then
              break
            fi
            sleep 10
          done
